from __future__ import annotations

from typing import Any

from autodq.knowledge.rules import KnowledgeRule


def _rule(
    name: str,
    *,
    semantic_type: str,
    expected_min: float | None = None,
    expected_max: float | None = None,
    allow_negative: bool | None = None,
    preferred_imputation: str | None = None,
    preferred_outlier_strategy: str | None = None,
    notes: tuple[str, ...] = (),
    domains: tuple[str, ...] = (),
    metadata: dict[str, Any] | None = None,
) -> KnowledgeRule:
    rule_metadata = dict(metadata or {})
    if domains:
        rule_metadata["domains"] = list(domains)

    return KnowledgeRule(
        name=name,
        semantic_type=semantic_type,
        expected_min=expected_min,
        expected_max=expected_max,
        allow_negative=allow_negative,
        preferred_imputation=preferred_imputation,
        preferred_outlier_strategy=preferred_outlier_strategy,
        notes=list(notes),
        metadata=rule_metadata,
    )


# This catalog deliberately contains conservative, reusable knowledge. Rules with
# universal ranges are explicit; fields whose valid range depends on the business
# keep that decision for review instead of pretending one threshold fits every
# dataset.
DEFAULT_KNOWLEDGE_RULES = {
    # People and identity
    "age": _rule(
        "age",
        semantic_type="continuous_numeric",
        expected_min=0,
        expected_max=120,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=(
            "Age usually falls between 0 and 120; confirm infant and historical "
            "records before correction.",
        ),
        domains=("demographics", "healthcare", "education", "hr"),
    ),
    "identifier": _rule(
        "identifier",
        semantic_type="identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Identifiers should normally be unique, stable, and treated as labels rather than measurements.",),
        domains=("general",),
        metadata={"quality_checks": ["uniqueness", "missingness", "format_consistency"]},
    ),
    "transaction_id": _rule(
        "transaction_id",
        semantic_type="transaction_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Transaction identifiers should be unique unless the dataset intentionally contains line items.",),
        domains=("retail", "banking", "payments"),
        metadata={"quality_checks": ["uniqueness", "missingness"]},
    ),
    "customer_id": _rule(
        "customer_id",
        semantic_type="customer_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Customer identifiers are join keys; missing or duplicated values require source-system review.",),
        domains=("crm", "retail", "subscription"),
    ),
    "account_id": _rule(
        "account_id",
        semantic_type="account_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Account identifiers are sensitive join keys and should not be statistically imputed.",),
        domains=("banking", "finance", "subscription"),
        metadata={"sensitivity": "potentially_sensitive"},
    ),
    "order_id": _rule(
        "order_id",
        semantic_type="order_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Order identifiers may repeat for line-item datasets but should be complete and consistently formatted.",),
        domains=("retail", "ecommerce", "logistics"),
    ),
    "product_id": _rule(
        "product_id",
        semantic_type="product_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Product identifiers should agree with the product catalog and are not numeric measurements.",),
        domains=("retail", "manufacturing", "inventory"),
    ),
    "employee_id": _rule(
        "employee_id",
        semantic_type="employee_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Employee identifiers are sensitive join keys and should not be inferred from neighboring rows.",),
        domains=("hr", "workforce"),
        metadata={"sensitivity": "potentially_sensitive"},
    ),
    "patient_id": _rule(
        "patient_id",
        semantic_type="patient_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Patient identifiers are sensitive and require strict completeness, uniqueness, and access controls.",),
        domains=("healthcare",),
        metadata={"sensitivity": "sensitive"},
    ),
    "student_id": _rule(
        "student_id",
        semantic_type="student_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Student identifiers are sensitive join keys and should not be statistically imputed.",),
        domains=("education",),
        metadata={"sensitivity": "potentially_sensitive"},
    ),
    "policy_id": _rule(
        "policy_id",
        semantic_type="policy_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Policy identifiers should match the policy administration source and remain text-safe.",),
        domains=("insurance",),
    ),
    "claim_id": _rule(
        "claim_id",
        semantic_type="claim_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Claim identifiers are business keys; repeats may be valid for claim-line datasets.",),
        domains=("insurance", "healthcare"),
    ),
    "device_id": _rule(
        "device_id",
        semantic_type="device_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Device identifiers are categorical keys even when they contain only digits.",),
        domains=("iot", "telecommunications"),
    ),
    "sensor_id": _rule(
        "sensor_id",
        semantic_type="sensor_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Sensor identifiers should be validated against the device registry before filling gaps.",),
        domains=("iot", "manufacturing"),
    ),
    "sku": _rule(
        "sku",
        semantic_type="stock_keeping_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("SKUs are catalog identifiers; preserve leading zeroes and validate against the product master.",),
        domains=("retail", "inventory", "manufacturing"),
    ),
    "tracking_number": _rule(
        "tracking_number",
        semantic_type="shipment_identifier",
        preferred_imputation="do_not_impute_without_context",
        notes=("Tracking numbers are carrier-issued text identifiers and may contain leading zeroes.",),
        domains=("logistics", "shipping"),
    ),
    "name": _rule(
        "name",
        semantic_type="name_text",
        preferred_imputation="do_not_impute_without_context",
        notes=("Names are free text, may be sensitive, and should not be guessed from statistical patterns.",),
        domains=("general",),
        metadata={"sensitivity": "potentially_sensitive"},
    ),
    "email": _rule(
        "email",
        semantic_type="email_address",
        preferred_imputation="do_not_impute_without_context",
        notes=("Email fields benefit from syntax, casing, whitespace, and duplicate-account checks.",),
        domains=("crm", "marketing", "hr"),
        metadata={"sensitivity": "personal", "format": "email"},
    ),
    "phone": _rule(
        "phone",
        semantic_type="phone_number",
        preferred_imputation="do_not_impute_without_context",
        notes=("Phone numbers are text identifiers; preserve country codes and leading zeroes.",),
        domains=("crm", "healthcare", "hr"),
        metadata={"sensitivity": "personal", "format": "phone"},
    ),
    # Time
    "date": _rule(
        "date",
        semantic_type="datetime",
        preferred_imputation="do_not_impute_without_context",
        notes=("Date fields should be parsed explicitly and checked for impossible or future values in context.",),
        domains=("general",),
    ),
    "time": _rule(
        "time",
        semantic_type="time_or_datetime",
        preferred_imputation="do_not_impute_without_context",
        notes=("Time fields require an explicit format and, when relevant, a timezone policy.",),
        domains=("general",),
    ),
    "duration": _rule(
        "duration",
        semantic_type="duration",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_cap",
        notes=("Durations are normally non-negative; verify the unit before comparing or imputing values.",),
        domains=("operations", "web_analytics", "healthcare"),
        metadata={"unit_required": True},
    ),
    "year": _rule(
        "year",
        semantic_type="calendar_year",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="do_not_impute_without_context",
        preferred_outlier_strategy="domain_range_check",
        notes=("Year values should be checked against the dataset's historical and forecasting horizon.",),
        domains=("general",),
    ),
    # Money and commercial measures
    "revenue": _rule(
        "revenue",
        semantic_type="currency",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Revenue is usually non-negative, but valid high-value business events should be preserved.",),
        domains=("finance", "retail", "sales"),
    ),
    "sales": _rule(
        "sales",
        semantic_type="currency_or_count",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Sales may represent money or units; confirm the measure and currency before treatment.",),
        domains=("retail", "sales"),
        metadata={"unit_required": True},
    ),
    "profit": _rule(
        "profit",
        semantic_type="currency",
        allow_negative=True,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Profit may legitimately be negative depending on returns, costs, and accounting context.",),
        domains=("finance", "retail"),
    ),
    "amount": _rule(
        "amount",
        semantic_type="currency_or_measure",
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Amount fields need their transaction type and currency before a sign or range rule is applied.",),
        domains=("finance", "payments", "insurance"),
        metadata={"context_required": ["currency", "transaction_type"]},
    ),
    "unit_price": _rule(
        "unit_price",
        semantic_type="currency",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Unit price is normally non-negative and should use a consistent currency and unit basis.",),
        domains=("retail", "procurement", "manufacturing"),
    ),
    "price": _rule(
        "price",
        semantic_type="currency",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Prices are normally non-negative; zero values may indicate promotions, samples, or missing data.",),
        domains=("retail", "ecommerce"),
    ),
    "cost": _rule(
        "cost",
        semantic_type="currency",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Costs are normally non-negative, although accounting reversals require contextual review.",),
        domains=("finance", "procurement", "manufacturing"),
    ),
    "expense": _rule(
        "expense",
        semantic_type="currency",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Expenses are usually non-negative; reimbursements and reversals may be exceptions.",),
        domains=("finance", "hr"),
    ),
    "balance": _rule(
        "balance",
        semantic_type="currency_balance",
        allow_negative=True,
        preferred_imputation="do_not_impute_without_context",
        preferred_outlier_strategy="review_only",
        notes=("Balances may be negative and should be reconciled to an account and effective date.",),
        domains=("banking", "finance"),
    ),
    "income": _rule(
        "income",
        semantic_type="currency",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Income is sensitive and often right-skewed; preserve plausible high values.",),
        domains=("finance", "demographics"),
        metadata={"sensitivity": "sensitive"},
    ),
    "salary": _rule(
        "salary",
        semantic_type="currency",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Salary is sensitive, non-negative, and may use annual, monthly, hourly, or total-compensation units.",),
        domains=("hr", "finance"),
        metadata={"sensitivity": "sensitive", "unit_required": True},
    ),
    "tax": _rule(
        "tax",
        semantic_type="currency_or_rate",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Tax may be an amount or rate and must follow the relevant jurisdiction and transaction context.",),
        domains=("finance", "retail"),
    ),
    "discount": _rule(
        "discount",
        semantic_type="percentage_or_amount",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Discounts are normally non-negative but may be stored as a fraction, percentage, or amount.",),
        domains=("retail", "sales"),
        metadata={"scale_requires_review": True},
    ),
    "percentage": _rule(
        "percentage",
        semantic_type="percentage_or_ratio",
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Confirm whether values use a 0-1 ratio or 0-100 percentage scale before validation.",),
        domains=("general",),
        metadata={"scale_requires_review": True},
    ),
    "interest_rate": _rule(
        "interest_rate",
        semantic_type="percentage_or_ratio",
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Interest rates need a period, compounding convention, and 0-1 versus 0-100 scale.",),
        domains=("banking", "finance"),
        metadata={"scale_requires_review": True},
    ),
    "margin": _rule(
        "margin",
        semantic_type="percentage_or_amount",
        allow_negative=True,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Margins may be negative and may be stored as an amount, ratio, or percentage.",),
        domains=("finance", "retail"),
        metadata={"scale_requires_review": True},
    ),
    "premium": _rule(
        "premium",
        semantic_type="currency",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_winsorize",
        notes=("Insurance premiums are normally non-negative and tied to a coverage period and policy.",),
        domains=("insurance",),
    ),
    "credit_score": _rule(
        "credit_score",
        semantic_type="bounded_score",
        expected_min=0,
        expected_max=1000,
        allow_negative=False,
        preferred_imputation="do_not_impute_without_context",
        preferred_outlier_strategy="domain_range_check",
        notes=("Credit-score ranges vary by provider; the broad 0-1000 bound still requires provider validation.",),
        domains=("banking", "lending"),
        metadata={"sensitivity": "sensitive"},
    ),
    # Counts, inventory, and physical measures
    "quantity": _rule(
        "quantity",
        semantic_type="discrete_numeric",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_cap",
        notes=("Quantities are normally whole and non-negative; returns may be represented separately or with signs.",),
        domains=("retail", "inventory", "manufacturing"),
    ),
    "count": _rule(
        "count",
        semantic_type="count",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_cap",
        notes=("Counts are normally whole and non-negative; distinguish a true zero from missing observation.",),
        domains=("general",),
    ),
    "inventory": _rule(
        "inventory",
        semantic_type="inventory_count",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_cap",
        notes=("Inventory is normally non-negative, but backorders and system timing can create exceptions.",),
        domains=("retail", "warehouse", "manufacturing"),
    ),
    "distance": _rule(
        "distance",
        semantic_type="physical_measure",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_cap",
        notes=("Distances are non-negative and require a consistent unit such as km, miles, or meters.",),
        domains=("logistics", "transportation", "geospatial"),
        metadata={"unit_required": True},
    ),
    "weight": _rule(
        "weight",
        semantic_type="physical_measure",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_cap",
        notes=("Weight is non-negative and requires a consistent unit before comparison.",),
        domains=("logistics", "healthcare", "manufacturing"),
        metadata={"unit_required": True},
    ),
    "height": _rule(
        "height",
        semantic_type="physical_measure",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_cap",
        notes=("Height is non-negative and requires a consistent unit before comparison.",),
        domains=("healthcare", "manufacturing"),
        metadata={"unit_required": True},
    ),
    "temperature": _rule(
        "temperature",
        semantic_type="temperature_measure",
        allow_negative=True,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Temperature may be negative and must identify Celsius, Fahrenheit, or Kelvin.",),
        domains=("iot", "weather", "healthcare", "manufacturing"),
        metadata={"unit_required": True},
    ),
    "humidity": _rule(
        "humidity",
        semantic_type="percentage_or_ratio",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Relative humidity is non-negative and commonly uses a 0-100 scale.",),
        domains=("iot", "weather", "agriculture"),
        metadata={"scale_requires_review": True},
    ),
    "pressure": _rule(
        "pressure",
        semantic_type="physical_measure",
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Pressure requires a known unit and domain-specific operating range.",),
        domains=("iot", "weather", "healthcare", "manufacturing"),
        metadata={"unit_required": True},
    ),
    # Geography and contact data
    "region": _rule(
        "region",
        semantic_type="geographic_category",
        preferred_imputation="mode",
        notes=("Regions are categorical and should use a controlled, consistently cased vocabulary.",),
        domains=("general",),
    ),
    "country": _rule(
        "country",
        semantic_type="country_category",
        preferred_imputation="mode",
        notes=("Country values should use one naming or ISO-code standard throughout the dataset.",),
        domains=("geospatial", "crm", "logistics"),
    ),
    "state_province": _rule(
        "state_province",
        semantic_type="administrative_area",
        preferred_imputation="mode",
        notes=("State and province values should be validated together with country and use one code standard.",),
        domains=("geospatial", "crm", "logistics"),
    ),
    "city": _rule(
        "city",
        semantic_type="city_name",
        preferred_imputation="mode",
        notes=("City names are categorical text and should be checked with state or country context.",),
        domains=("geospatial", "crm", "logistics"),
    ),
    "postal_code": _rule(
        "postal_code",
        semantic_type="postal_code",
        preferred_imputation="do_not_impute_without_context",
        notes=("Postal codes are text, may contain letters or leading zeroes, and depend on country format.",),
        domains=("geospatial", "crm", "logistics"),
    ),
    "address": _rule(
        "address",
        semantic_type="street_address",
        preferred_imputation="do_not_impute_without_context",
        notes=("Addresses are sensitive free text and need parsing, normalization, and country context.",),
        domains=("crm", "logistics"),
        metadata={"sensitivity": "personal"},
    ),
    "latitude": _rule(
        "latitude",
        semantic_type="latitude",
        expected_min=-90,
        expected_max=90,
        allow_negative=True,
        preferred_imputation="do_not_impute_without_context",
        preferred_outlier_strategy="domain_range_check",
        notes=("Latitude must fall between -90 and 90 degrees.",),
        domains=("geospatial",),
        metadata={"unit": "degrees"},
    ),
    "longitude": _rule(
        "longitude",
        semantic_type="longitude",
        expected_min=-180,
        expected_max=180,
        allow_negative=True,
        preferred_imputation="do_not_impute_without_context",
        preferred_outlier_strategy="domain_range_check",
        notes=("Longitude must fall between -180 and 180 degrees.",),
        domains=("geospatial",),
        metadata={"unit": "degrees"},
    ),
    # Categories and descriptive fields
    "gender": _rule(
        "gender",
        semantic_type="categorical",
        preferred_imputation="mode",
        notes=("Gender and sex fields are sensitive categories; preserve the source vocabulary and document its meaning.",),
        domains=("demographics", "healthcare", "hr"),
        metadata={"sensitivity": "sensitive"},
    ),
    "product": _rule(
        "product",
        semantic_type="product_category",
        preferred_imputation="mode",
        notes=("Product values should align with a catalog or controlled business vocabulary.",),
        domains=("retail", "inventory", "manufacturing"),
    ),
    "category": _rule(
        "category",
        semantic_type="categorical",
        preferred_imputation="mode",
        notes=("Category fields should use a controlled vocabulary with consistent spelling and casing.",),
        domains=("general",),
    ),
    "status": _rule(
        "status",
        semantic_type="status_category",
        preferred_imputation="mode",
        notes=("Status values should follow an allowed lifecycle vocabulary and valid state transitions.",),
        domains=("general",),
    ),
    "boolean_flag": _rule(
        "boolean_flag",
        semantic_type="boolean",
        preferred_imputation="do_not_impute_without_context",
        notes=("Boolean flags should use one encoding and distinguish false from unknown or missing.",),
        domains=("general",),
    ),
    "description": _rule(
        "description",
        semantic_type="free_text",
        preferred_imputation="do_not_impute_without_context",
        notes=("Free-text descriptions should not be statistically imputed; inspect encoding, length, and sensitive content.",),
        domains=("general",),
    ),
    "url": _rule(
        "url",
        semantic_type="url",
        preferred_imputation="do_not_impute_without_context",
        notes=("URLs should be validated for scheme, host, whitespace, and safe normalization.",),
        domains=("web", "marketing"),
        metadata={"format": "url"},
    ),
    "ip_address": _rule(
        "ip_address",
        semantic_type="ip_address",
        preferred_imputation="do_not_impute_without_context",
        notes=("IP addresses are identifiers, not numbers, and may be sensitive or regulated.",),
        domains=("web", "security", "telecommunications"),
        metadata={"sensitivity": "potentially_sensitive"},
    ),
    "department": _rule(
        "department",
        semantic_type="organizational_category",
        preferred_imputation="mode",
        notes=("Departments should align with the organization's controlled hierarchy.",),
        domains=("hr", "finance"),
    ),
    "job_title": _rule(
        "job_title",
        semantic_type="job_category",
        preferred_imputation="mode",
        notes=("Job titles often need normalization to a controlled role or occupation taxonomy.",),
        domains=("hr",),
    ),
    "channel": _rule(
        "channel",
        semantic_type="channel_category",
        preferred_imputation="mode",
        notes=("Channel values should use a controlled set such as online, store, partner, email, or social.",),
        domains=("sales", "marketing", "retail"),
    ),
    "payment_method": _rule(
        "payment_method",
        semantic_type="payment_category",
        preferred_imputation="mode",
        notes=("Payment methods should use a controlled vocabulary and avoid storing raw payment credentials.",),
        domains=("payments", "retail"),
        metadata={"sensitivity": "potentially_sensitive"},
    ),
    "currency_code": _rule(
        "currency_code",
        semantic_type="currency_code",
        preferred_imputation="mode",
        notes=("Currency should use a consistent ISO 4217 code when monetary fields span currencies.",),
        domains=("finance", "payments", "retail"),
        metadata={"format": "ISO_4217"},
    ),
    # Scores, outcomes, healthcare, education, and marketing
    "rating": _rule(
        "rating",
        semantic_type="bounded_score",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Ratings require the declared scale, such as 1-5 or 0-10, before a maximum is enforced.",),
        domains=("customer_experience", "hr", "retail"),
        metadata={"scale_requires_review": True},
    ),
    "score": _rule(
        "score",
        semantic_type="bounded_score",
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Scores require a documented minimum, maximum, and direction before range validation.",),
        domains=("education", "risk", "customer_experience"),
        metadata={"scale_requires_review": True},
    ),
    "satisfaction": _rule(
        "satisfaction",
        semantic_type="ordinal_score",
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Satisfaction is usually ordinal; confirm its survey scale before enforcing a range.",),
        domains=("customer_experience", "hr"),
        metadata={"scale_requires_review": True},
    ),
    "probability": _rule(
        "probability",
        semantic_type="probability",
        expected_min=0,
        expected_max=1,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Probabilities and model confidence values should fall between 0 and 1.",),
        domains=("machine_learning", "risk"),
    ),
    "bmi": _rule(
        "bmi",
        semantic_type="health_measure",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("BMI is non-negative; clinical interpretation and plausible ranges require domain oversight.",),
        domains=("healthcare",),
        metadata={"sensitivity": "health"},
    ),
    "blood_pressure": _rule(
        "blood_pressure",
        semantic_type="health_measure",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="do_not_impute_without_context",
        preferred_outlier_strategy="domain_range_check",
        notes=("Blood pressure needs systolic/diastolic meaning and units; clinical thresholds require expert oversight.",),
        domains=("healthcare",),
        metadata={"sensitivity": "health", "unit_required": True},
    ),
    "heart_rate": _rule(
        "heart_rate",
        semantic_type="health_measure",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Heart rate is non-negative, but valid ranges depend on patient, activity, and measurement context.",),
        domains=("healthcare", "wearables"),
        metadata={"sensitivity": "health", "unit": "beats_per_minute"},
    ),
    "diagnosis": _rule(
        "diagnosis",
        semantic_type="clinical_category",
        preferred_imputation="do_not_impute_without_context",
        notes=("Diagnosis values are sensitive clinical categories and should use a documented coding system.",),
        domains=("healthcare",),
        metadata={"sensitivity": "health"},
    ),
    "medication": _rule(
        "medication",
        semantic_type="clinical_category",
        preferred_imputation="do_not_impute_without_context",
        notes=("Medication values are sensitive and should be normalized against a trusted drug vocabulary.",),
        domains=("healthcare",),
        metadata={"sensitivity": "health"},
    ),
    "grade": _rule(
        "grade",
        semantic_type="education_score_or_category",
        preferred_imputation="do_not_impute_without_context",
        preferred_outlier_strategy="domain_range_check",
        notes=("Grades may be letters, percentages, points, or levels; validate against the declared grading system.",),
        domains=("education",),
        metadata={"scale_requires_review": True},
    ),
    "gpa": _rule(
        "gpa",
        semantic_type="education_score",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="do_not_impute_without_context",
        preferred_outlier_strategy="domain_range_check",
        notes=("GPA is non-negative but its maximum varies by institution and weighting policy.",),
        domains=("education",),
        metadata={"scale_requires_review": True},
    ),
    "attendance": _rule(
        "attendance",
        semantic_type="count_or_percentage",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Attendance may be a count, ratio, or percentage and needs a declared period and scale.",),
        domains=("education", "hr"),
        metadata={"scale_requires_review": True},
    ),
    "impressions": _rule(
        "impressions",
        semantic_type="count",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_cap",
        notes=("Impressions are non-negative counts and may contain valid campaign spikes.",),
        domains=("marketing", "web_analytics"),
    ),
    "clicks": _rule(
        "clicks",
        semantic_type="count",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="review_or_cap",
        notes=("Clicks are non-negative counts and should not exceed impressions at the same aggregation level.",),
        domains=("marketing", "web_analytics"),
    ),
    "conversion_rate": _rule(
        "conversion_rate",
        semantic_type="percentage_or_ratio",
        expected_min=0,
        allow_negative=False,
        preferred_imputation="median",
        preferred_outlier_strategy="domain_range_check",
        notes=("Conversion rate must use a known 0-1 or 0-100 scale and a consistent denominator.",),
        domains=("marketing", "sales", "web_analytics"),
        metadata={"scale_requires_review": True},
    ),
    "campaign": _rule(
        "campaign",
        semantic_type="campaign_category",
        preferred_imputation="mode",
        notes=("Campaign values should align with the marketing campaign registry and reporting hierarchy.",),
        domains=("marketing",),
    ),
}


# Aliases are kept outside KnowledgeRule.metadata so KNOWLEDGE output stays useful
# instead of dumping a large implementation vocabulary for every matched column.
DEFAULT_KNOWLEDGE_ALIASES: dict[str, tuple[str, ...]] = {
    "age": ("customer_age", "patient_age", "employee_age", "student_age", "user_age"),
    "identifier": ("id", "record_id", "row_id", "uuid", "guid", "key", "record_key"),
    "transaction_id": ("transaction", "transaction_number", "txn_id", "txn_number", "payment_id"),
    "customer_id": ("customer_number", "client_id", "client_number", "consumer_id", "member_id"),
    "account_id": ("account_number", "acct_id", "acct_number", "subscription_id"),
    "order_id": ("order_number", "purchase_order", "po_number", "invoice_id", "invoice_number"),
    "product_id": ("product_code", "item_id", "item_code", "material_id", "material_code"),
    "employee_id": ("employee_number", "staff_id", "worker_id", "personnel_number"),
    "patient_id": ("patient_number", "medical_record_number", "mrn"),
    "student_id": ("student_number", "learner_id", "pupil_id"),
    "policy_id": ("policy_number", "policy_no"),
    "claim_id": ("claim_number", "claim_no"),
    "device_id": ("device_identifier", "machine_id", "equipment_id", "terminal_id"),
    "sensor_id": ("sensor_identifier", "probe_id", "meter_id"),
    "sku": ("stock_keeping_unit", "part_number", "part_no"),
    "tracking_number": ("tracking_id", "shipment_id", "consignment_number", "waybill"),
    "name": ("full_name", "first_name", "last_name", "given_name", "family_name", "company_name"),
    "email": ("email_address", "e_mail", "contact_email", "work_email"),
    "phone": ("phone_number", "mobile", "mobile_number", "telephone", "contact_number"),
    "date": (
        "datetime", "birth_date", "date_of_birth", "dob", "created_at", "updated_at",
        "start_date", "end_date", "due_date", "order_date", "invoice_date", "hire_date",
        "admission_date", "discharge_date", "delivery_date", "event_date",
    ),
    "time": ("timestamp", "event_time", "created_time", "updated_time", "time_of_day"),
    "duration": (
        "elapsed_time", "response_time", "processing_time", "lead_time", "wait_time",
        "session_duration", "trip_duration", "delivery_days", "days_to_delivery", "tenure",
    ),
    "year": ("calendar_year", "fiscal_year", "birth_year", "model_year"),
    "revenue": ("total_revenue", "net_revenue", "gross_revenue", "turnover"),
    "sales": ("gross_sales", "net_sales", "sales_value", "sales_amount"),
    "profit": ("gross_profit", "net_profit", "operating_profit", "earnings"),
    "amount": (
        "transaction_amount", "payment_amount", "claim_amount", "loan_amount", "order_amount",
        "invoice_amount", "total_amount", "gross_amount", "net_amount",
    ),
    "unit_price": ("price_per_unit", "sale_price", "selling_price", "list_price"),
    "price": ("purchase_price", "retail_price", "wholesale_price", "market_price"),
    "cost": ("unit_cost", "total_cost", "product_cost", "acquisition_cost", "cogs"),
    "expense": ("expenses", "operating_expense", "opex", "travel_expense"),
    "balance": ("account_balance", "current_balance", "available_balance", "outstanding_balance"),
    "income": ("annual_income", "monthly_income", "household_income", "gross_income", "net_income"),
    "salary": ("annual_salary", "base_salary", "wage", "wages", "compensation", "pay_rate"),
    "tax": ("tax_amount", "tax_rate", "vat", "gst", "sales_tax"),
    "discount": ("discount_amount", "discount_rate", "discount_percentage", "markdown"),
    "percentage": ("percent", "percentage", "pct", "ratio", "rate"),
    "interest_rate": ("apr", "annual_percentage_rate", "mortgage_rate", "loan_rate"),
    "margin": ("profit_margin", "gross_margin", "operating_margin", "markup"),
    "premium": ("insurance_premium", "annual_premium", "monthly_premium"),
    "credit_score": ("fico", "fico_score", "risk_score", "bureau_score"),
    "quantity": ("qty", "units", "units_sold", "order_quantity", "item_quantity"),
    "count": ("total_count", "number_of_items", "num_items", "frequency", "occurrences"),
    "inventory": ("stock", "stock_level", "stock_quantity", "inventory_level", "on_hand", "units_in_stock"),
    "distance": ("distance_km", "distance_miles", "travel_distance", "trip_distance"),
    "weight": ("weight_kg", "weight_lb", "body_weight", "shipment_weight"),
    "height": ("height_cm", "height_m", "body_height", "length"),
    "temperature": ("temp", "temperature_c", "temperature_f", "body_temperature", "air_temperature"),
    "humidity": ("relative_humidity", "humidity_percent"),
    "pressure": ("air_pressure", "barometric_pressure", "systolic_pressure", "diastolic_pressure"),
    "region": ("sales_region", "market_region", "territory", "zone"),
    "country": ("country_name", "country_code", "nation", "iso_country"),
    "state_province": ("state", "province", "state_code", "province_code", "administrative_area"),
    "city": ("city_name", "town", "municipality"),
    "postal_code": ("postcode", "zip", "zip_code", "zipcode", "postal", "pin_code"),
    "address": ("street_address", "address_line", "address_line_1", "mailing_address", "billing_address"),
    "latitude": ("lat", "geo_latitude", "gps_latitude"),
    "longitude": ("lon", "lng", "long", "geo_longitude", "gps_longitude"),
    "gender": ("sex", "gender_identity"),
    "product": ("product_name", "item", "item_name", "service", "service_name"),
    "category": ("type", "class", "segment", "group", "subcategory", "customer_segment"),
    "status": ("order_status", "account_status", "payment_status", "claim_status", "state_status"),
    "boolean_flag": (
        "flag", "is_active", "active", "enabled", "is_deleted", "deleted", "returned",
        "refunded", "churned", "defaulted", "fraud_flag", "is_fraud", "has_discount",
    ),
    "description": ("desc", "details", "comment", "comments", "notes", "remarks", "free_text", "summary"),
    "url": ("website", "web_url", "page_url", "link", "uri"),
    "ip_address": ("ip", "ipv4", "ipv6", "client_ip", "source_ip"),
    "department": ("department_name", "dept", "business_unit", "division", "team"),
    "job_title": ("position", "role", "occupation", "job_role", "designation"),
    "channel": ("sales_channel", "marketing_channel", "acquisition_channel", "source_channel"),
    "payment_method": ("payment_type", "tender_type", "card_type", "payment_channel"),
    "currency_code": ("currency", "currency_iso", "iso_currency"),
    "rating": ("star_rating", "review_rating", "performance_rating", "risk_rating"),
    "score": ("test_score", "exam_score", "quality_score", "performance_score", "index_score"),
    "satisfaction": ("customer_satisfaction", "satisfaction_score", "csat", "nps"),
    "probability": ("probability_score", "confidence", "confidence_score", "propensity", "likelihood"),
    "bmi": ("body_mass_index",),
    "blood_pressure": ("bp", "blood_pressure_reading"),
    "heart_rate": ("pulse", "pulse_rate", "bpm"),
    "diagnosis": ("diagnosis_code", "condition", "condition_code", "icd_code"),
    "medication": ("medicine", "drug", "drug_name", "medication_name", "rxnorm_code"),
    "grade": ("letter_grade", "final_grade", "course_grade", "grade_level"),
    "gpa": ("grade_point_average",),
    "attendance": ("attendance_rate", "days_present", "days_absent", "absence_count"),
    "impressions": ("ad_impressions", "page_impressions", "views", "page_views"),
    "clicks": ("ad_clicks", "link_clicks", "click_count"),
    "conversion_rate": ("conversion", "conversion_percent", "cvr", "close_rate"),
    "campaign": ("campaign_id", "campaign_name", "promotion", "promotion_name"),
}
